using System.ComponentModel;
using System.Globalization;
using System.Windows.Data;

namespace GitTab.App.Localization;

/// <summary>
/// In-memory ko/en string tables with a live language toggle. Beginner-oriented ".Tip" strings
/// explain each Git action in plain language for first-time users.
/// </summary>
public sealed partial class LocalizationService : ILocalizationService
{
    public static LocalizationService Current { get; private set; } = new();

    private AppLanguage _language = AppLanguage.Korean;

    public LocalizationService() => Current = this;

    public event PropertyChangedEventHandler? PropertyChanged;
    public event EventHandler? LanguageChanged;

    public AppLanguage Language
    {
        get => _language;
        set
        {
            if (_language == value) return;
            _language = value;
            // Refresh every indexer binding and notify listeners.
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(Binding.IndexerName));
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Language)));
            LanguageChanged?.Invoke(this, EventArgs.Empty);
        }
    }

    public string this[string key] => T(key);

    public string T(string key)
    {
        if (Table(_language).TryGetValue(key, out var value)) return value;
        // Fall back to English (the reference table), then the key itself.
        return En.TryGetValue(key, out var alt) ? alt : key;
    }

    private static Dictionary<string, string> Table(AppLanguage lang) => lang switch
    {
        AppLanguage.Korean => Ko,
        AppLanguage.Japanese => Ja,
        AppLanguage.Chinese => Zh,
        AppLanguage.Spanish => Es,
        _ => En
    };

    public string T(string key, params object[] args)
    {
        try { return string.Format(CultureInfo.CurrentCulture, T(key), args); }
        catch (FormatException) { return T(key); }
    }

    public void Toggle() => Language = _language switch
    {
        AppLanguage.Korean => AppLanguage.English,
        AppLanguage.English => AppLanguage.Japanese,
        AppLanguage.Japanese => AppLanguage.Chinese,
        AppLanguage.Chinese => AppLanguage.Spanish,
        _ => AppLanguage.Korean
    };

    // ---------------------------------------------------------------- string tables

    private static readonly Dictionary<string, string> Ko = new(StringComparer.Ordinal)
    {
        ["App.Title"] = "Git Tab",

        // Toolbar / actions
        ["Action.Open"] = "저장소 열기",
        ["Action.Open.Tip"] = "컴퓨터에서 Git 저장소 폴더를 골라 열어요.",
        ["Action.Refresh"] = "새로고침",
        ["Action.Refresh.Tip"] = "저장소의 최신 상태를 다시 읽어와요.",
        ["Undo.Title"] = "실행 취소",
        ["Undo.Tip"] = "마지막 Git 작업을 되돌려요(reflog 기반). 커밋을 취소하면 변경 내용은 스테이지에 남고, 그 외에는 직전 상태로 돌아가요. 작업하지 않은 로컬 변경은 보호돼요.",
        ["Undo.Confirm"] = "마지막 작업을 되돌릴까요?\n\n작업: {0}\n\n직전 상태로 돌아가요. (커밋/amend를 취소하면 변경 내용은 스테이지에 남아요.)",
        ["Action.Recent"] = "최근 저장소",
        ["Action.Recent.Empty"] = "최근 연 저장소가 없어요",
        ["Action.Fetch"] = "가져오기",
        ["Action.Fetch.Tip"] = "원격 저장소의 최신 커밋 정보를 내려받아요. 내 파일이나 브랜치는 바뀌지 않으니 안심하고 눌러도 돼요.",
        ["Action.Pull"] = "받아오기",
        ["Action.Pull.Tip"] = "원격의 변경을 가져와서 현재 브랜치에 합쳐요(fetch + merge).",
        ["Action.Push"] = "올리기",
        ["Action.Push.Tip"] = "내 커밋을 원격 저장소로 보내요. 인증은 시스템 Git 자격 증명 도우미가 처리해요.",
        ["Action.Commit"] = "커밋",

        // 복제 (Clone)
        ["Clone.Title"] = "저장소 복제",
        ["Clone.Action"] = "복제",
        ["Clone.Tip"] = "원격 저장소 주소(URL)를 받아 내 컴퓨터로 복제(clone)해요.",
        ["Clone.Url"] = "원격 저장소 주소 (URL)",
        ["Clone.Parent"] = "받을 위치 (상위 폴더)",
        ["Clone.FolderName"] = "폴더 이름",

        // 저장소 만들기 / 원격
        ["Repo.Create"] = "저장소 만들기",
        ["Repo.Create.Tip"] = "폴더를 골라 새 Git 저장소를 만들어요(git init). 원격 주소도 함께 연결할 수 있어요.",
        ["Repo.Create.Tip.Short"] = "새 Git 저장소를 만들어요.",
        ["Repo.Folder"] = "폴더",
        ["Repo.Browse"] = "찾아보기…",
        ["Repo.InitialBranch"] = "초기 브랜치 이름",
        ["Repo.RemoteOptional"] = "원격 주소 (선택)",
        ["Repo.Remote.Tip"] = "예: https://github.com/사용자/저장소.git — 비워 두면 나중에 ‘원격’에서 추가할 수 있어요.",
        ["Remote.Button"] = "원격",
        ["Remote.Manage"] = "원격 저장소 관리",
        ["Remote.Tip"] = "원격 저장소(예: origin) 주소를 추가·변경·삭제해요. Push/Pull이 향하는 곳이에요.",
        ["Remote.Add"] = "원격 추가",
        ["Remote.Edit"] = "주소 변경",
        ["Remote.EditUrl"] = "주소 변경",
        ["Remote.Remove"] = "원격 삭제",
        ["Remote.NamePrompt"] = "원격 이름을 입력하세요 (보통 origin)",
        ["Remote.UrlPrompt"] = "원격 저장소 주소(URL)를 입력하세요",
        ["Remote.RemoveConfirm"] = "‘{0}’ 원격을 삭제할까요? (로컬 커밋은 사라지지 않아요.)",

        // 호스팅 연동 (GitHub/GitLab)
        ["Hosting.PR"] = "PR 만들기",
        ["Hosting.PR.Tip"] = "현재 브랜치로 GitHub Pull Request / GitLab Merge Request 만들기 페이지를 브라우저로 열어요.",
        ["Hosting.Web"] = "웹에서 열기",
        ["Hosting.Web.Tip"] = "이 저장소의 원격 웹 페이지(GitHub/GitLab 등)를 브라우저로 열어요.",
        ["Hosting.Unsupported"] = "이 원격은 PR 만들기를 지원하지 않아요(GitHub·GitLab만 가능). 원격이 설정돼 있고 브랜치를 먼저 Push했는지 확인하세요.",
        ["Hosting.NoRemote"] = "열 수 있는 원격 웹 주소가 없어요.",

        // 작업 기록 / 되돌리기 (reflog)
        ["Reflog.Title"] = "작업 기록 · 되돌리기",
        ["Reflog.Tip"] = "최근에 HEAD가 지나온 지점들이에요. 커밋·머지·리셋을 잘못했어도 여기서 되돌릴 수 있어요.",
        ["Reflog.Reset"] = "이 지점으로",
        ["Reflog.ResetConfirm"] = "‘{0}’ 지점으로 되돌릴까요? (reset --hard — 저장하지 않은 변경은 사라져요.)",
        ["Reflog.UndoLast"] = "↩ 마지막 작업 취소",
        ["Reflog.UndoLast.Tip"] = "바로 직전 상태로 되돌려요(HEAD@{1}). 방금 한 작업을 취소할 때 편해요.",

        // Language / theme / search
        ["Language"] = "언어",
        ["Language.Korean"] = "한국어",
        ["Language.English"] = "English",
        ["Settings"] = "설정",
        ["Theme.Toggle"] = "테마 전환",
        ["Theme.Pick"] = "테마 선택",
        ["Theme.Light"] = "라이트",
        ["Theme.Dark"] = "다크",
        ["Search.Placeholder"] = "메시지 · 작성자 · 해시로 검색",
        ["Search.Tip"] = "커밋 메시지, 작성자 이름, 또는 커밋 해시로 걸러서 찾아요.",
        ["Palette.Placeholder"] = "명령 검색… (Ctrl+P)",
        ["Compare.Title"] = "브랜치/커밋 비교",
        ["Compare.Tip"] = "두 브랜치·태그·커밋 사이의 변경 파일과 diff를 비교해요.",
        ["Compare.From"] = "기준",
        ["Compare.To"] = "대상",
        ["Compare.Changed"] = "변경된 파일",
        ["Search.Content"] = "내용 검색",
        ["Search.Content.Tip"] = "코드에서 특정 문자열이 추가·삭제된 커밋을 찾아요(pickaxe). 정규식도 가능.",
        ["Search.Regex"] = "정규식",
        ["Search.Run"] = "검색",
        ["Search.Empty"] = "일치하는 커밋이 없어요.",
        ["Search.DblClick"] = "결과를 더블클릭하면 그 커밋으로 이동해요.",
        ["Search.NotInView"] = "그 커밋은 현재 목록에서 찾지 못했어요.",

        // Panels
        ["Panel.History"] = "히스토리",
        ["Panel.Changes"] = "변경사항",
        ["Panel.Branches"] = "브랜치",
        ["Panel.Details"] = "커밋 상세",
        ["Panel.Diff"] = "변경 내용",

        // Graph column headers
        ["Col.Refs"] = "브랜치 / 태그",
        ["Col.Graph"] = "그래프",
        ["Col.Message"] = "커밋 메시지",
        ["Col.Changes"] = "변경",
        ["Col.Author"] = "작성자",
        ["Col.Date"] = "커밋 날짜",
        ["Col.Sha"] = "SHA",

        // Welcome / onboarding
        ["Welcome.Title"] = "Git Tab에 오신 걸 환영해요",
        ["Welcome.Subtitle"] = "저장소 폴더를 열거나, 이 창으로 폴더를 끌어다 놓으세요.",
        ["Welcome.Open"] = "저장소 열기",
        ["Welcome.Hint"] = "Git이 처음인가요? 각 버튼에 마우스를 올리면 무엇을 하는지 설명이 나와요.",

        // Working copy / staging
        ["WC.Staged"] = "스테이지됨 (커밋에 포함될 변경)",
        ["WC.Unstaged"] = "스테이지 안 됨 (아직 커밋에 포함 안 됨)",
        ["WC.StageAll"] = "모두 스테이지",
        ["WC.StageAll.Tip"] = "모든 변경을 다음 커밋에 포함하도록 올려요.",
        ["WC.UnstageAll"] = "모두 내리기",
        ["WC.Stage.Tip"] = "이 파일의 변경을 다음 커밋에 포함하도록 올려둬요.",
        ["WC.StagePartial"] = "부분 스테이지",
        ["WC.StagePartial.Tip"] = "파일 전체가 아니라, 바뀐 부분(헝크)만 골라서 스테이지해요. (git add -p)",
        ["WC.StagePartial.StageHunk"] = "이 부분 스테이지",
        ["WC.StagePartial.Empty"] = "부분 스테이지할 변경이 없어요. (새 파일은 전체(+)로 올려요.)",
        ["WC.Unstage.Tip"] = "이 파일을 다음 커밋에서 빼요(변경 내용은 그대로 남아요).",
        ["WC.Discard"] = "변경 되돌리기",
        ["WC.Discard.Tip"] = "이 파일에서 수정한 내용을 버리고 마지막 커밋 상태로 되돌려요. ⚠ 되돌린 내용은 복구할 수 없어요.",
        ["WC.Type"] = "커밋 종류",
        ["WC.Type.Tip"] = "커밋 종류를 고르면 메시지 앞에 ‘feat:’, ‘fix:’ 처럼 자동으로 붙어요(Conventional Commits). 초보자도 일관된 메시지를 쉽게 쓸 수 있어요.",
        ["WC.CommitMessage.Placeholder"] = "무엇을, 왜 바꿨는지 적어요",
        ["WC.Amend"] = "마지막 커밋 고치기 (amend)",
        ["WC.Amend.Tip"] = "새 커밋을 만들지 않고, 방금 만든 마지막 커밋에 변경을 합치거나 메시지를 고쳐요.",
        ["WC.Commit"] = "커밋하기",
        ["WC.Commit.Tip"] = "스테이지된 변경을 하나의 커밋(스냅샷)으로 저장해요. 커밋은 나중에 다시 돌아올 수 있는 안전한 기록점이에요.",
        ["WC.NothingToCommit"] = "커밋할 변경이 없어요",
        ["WC.Clean"] = "변경사항이 없어요. 깨끗한 상태예요!",

        // Branches
        ["Branch.Local"] = "로컬 브랜치",
        ["Branch.Remote"] = "원격 브랜치",
        ["Branch.Checkout"] = "이 브랜치로 이동",
        ["Branch.Checkout.Tip"] = "이 브랜치로 전환해요. 작업 폴더의 파일이 그 브랜치의 상태로 바뀌어요.",
        ["Branch.New"] = "새 브랜치",
        ["Branch.New.Tip"] = "지금 위치에서 새 브랜치를 만들어요. 브랜치는 안전하게 실험할 수 있는 평행 작업 공간이에요.",
        ["Branch.Delete"] = "브랜치 삭제",
        ["Branch.Delete.Tip"] = "이 브랜치를 삭제해요. 아직 합쳐지지 않은 커밋이 있으면 경고해요.",
        ["Branch.Rename"] = "이름 바꾸기",
        ["Branch.Rename.Tip"] = "이 브랜치의 이름을 바꿔요.",
        ["Branch.Merge"] = "현재 브랜치에 병합",
        ["Branch.Merge.Tip"] = "선택한 브랜치의 변경을 지금 브랜치로 합쳐요.",
        ["Branch.Rebase"] = "리베이스",
        ["Branch.Rebase.Tip"] = "현재 브랜치의 커밋을 선택한 브랜치 위로 다시 쌓아요. 히스토리를 다시 쓰므로 주의하세요.",
        ["Branch.NewName.Prompt"] = "새 브랜치 이름을 입력하세요",
        ["Branch.RenamePrompt"] = "새 이름을 입력하세요",

        // Context-menu (TortoiseGit-style right-click)
        ["Ctx.CheckoutCommit"] = "이 커밋으로 체크아웃 (detached)",
        ["Ctx.Reword"] = "메시지 수정 (reword)",
        ["Reword.Title"] = "커밋 메시지 수정",
        ["Reword.Prompt"] = "새 커밋 메시지를 입력하세요. (마지막 커밋이 아니면 그 위 커밋들이 다시 쓰여요.)",
        ["Ctx.CreateBranch"] = "여기서 브랜치 생성",
        ["Ctx.CreateTag"] = "여기서 태그 생성",
        ["Ctx.ResetSoft"] = "여기로 Reset — soft (변경 보존)",
        ["Ctx.ResetMixed"] = "여기로 Reset — mixed (스테이지 해제)",
        ["Ctx.ResetHard"] = "여기로 Reset — hard ⚠ (변경 삭제)",
        ["Ctx.Revert"] = "이 커밋 되돌리기 (revert)",
        ["Ctx.CherryPick"] = "이 커밋 체리픽 (cherry-pick)",
        ["Ctx.CopySha"] = "커밋 해시(SHA) 복사",
        ["Ctx.CopyMessage"] = "커밋 메시지 복사",
        ["Ctx.OpenFile"] = "파일 열기",
        ["Ctx.CopyPath"] = "경로 복사",

        // .gitignore generator
        ["Gitignore.Button"] = ".gitignore",
        ["Gitignore.Title"] = ".gitignore 만들기",
        ["Gitignore.Tip"] = "프로젝트 스택을 감지해 알맞은 .gitignore를 만들어요. 빌드 산출물·캐시 등 버전관리에 넣지 않을 파일을 자동으로 제외해요.",
        ["Gitignore.Detected"] = "포함할 스택 (감지된 항목이 미리 선택됨)",
        ["Gitignore.Write"] = "생성 / 덮어쓰기",
        ["Gitignore.Append"] = "기존 파일에 추가",
        ["Gitignore.Exists"] = "이미 .gitignore가 있어요.",

        // In-progress operations / conflicts
        ["State.Merge"] = "머지 진행 중",
        ["State.Rebase"] = "리베이스 진행 중",
        ["State.CherryPick"] = "체리픽 진행 중",
        ["State.Revert"] = "되돌리기 진행 중",
        ["State.Bisect"] = "이분 탐색 진행 중",
        ["Ctx.StartBisect"] = "이 커밋부터 이분 탐색 (이 커밋은 정상)",
        ["Bisect.Title"] = "이분 탐색 (bisect)",
        ["Bisect.StartConfirm"] = "이 커밋을 '정상', 현재 HEAD를 '문제'로 이분 탐색을 시작할까요? 중간 커밋으로 체크아웃돼요.",
        ["Bisect.Good"] = "정상 ✓",
        ["Bisect.Good.Tip"] = "지금 체크아웃된 커밋에 문제가 없어요.",
        ["Bisect.Bad"] = "문제 ✗",
        ["Bisect.Bad.Tip"] = "지금 체크아웃된 커밋에 문제가 있어요.",
        ["Bisect.Skip"] = "건너뛰기",
        ["Bisect.Reset"] = "종료",
        ["Conflict.Hint"] = "충돌 파일을 해결(＋로 스테이지)한 뒤 ‘계속’을, 취소하려면 ‘중단’을 누르세요.",
        ["Conflict.Continue"] = "계속",
        ["Conflict.Abort"] = "중단",
        ["Conflict.Resolve"] = "충돌 해결",
        ["Conflict.ResolveHint"] = "각 충돌 구간에서 어느 쪽을 사용할지 고르세요. 적용하면 파일이 저장되고 해결됨으로 표시(스테이지)돼요.",
        ["Conflict.UseOurs"] = "내 것(ours)",
        ["Conflict.UseTheirs"] = "상대 것(theirs)",
        ["Conflict.Both"] = "둘 다",
        ["Conflict.Ours"] = "내 변경 (ours)",
        ["Conflict.Theirs"] = "상대 변경 (theirs)",
        ["Conflict.Base"] = "공통 조상 (base)",
        ["Conflict.NoBase"] = "(공통 조상 없음 — 새 파일이거나 병합 기준을 찾을 수 없어요)",
        ["Conflict.Result"] = "최종 결과 (직접 편집)",
        ["Conflict.UseOursAll"] = "내 것으로",
        ["Conflict.UseTheirsAll"] = "상대 것으로",
        ["Conflict.KeepBoth"] = "양쪽 유지(마커 제거)",
        ["Conflict.ApplyResolve"] = "해결 적용",

        // Stash
        ["Stash.Section"] = "스태시",
        ["Stash.Push"] = "변경 스태시",
        ["Stash.Push.Tip"] = "지금의 변경을 잠시 치워두고 작업 폴더를 깨끗하게 만들어요. 나중에 되살릴 수 있어요.",
        ["Stash.Pop"] = "적용 후 삭제 (pop)",
        ["Stash.Apply"] = "적용",
        ["Stash.Drop"] = "삭제",
        ["Stash.Empty"] = "스태시가 없어요",

        // Tags
        ["Tag.Section"] = "태그",
        ["Tag.Push"] = "원격에 올리기",
        ["Tag.Delete"] = "태그 삭제",
        ["Confirm.DeleteTagTitle"] = "태그를 삭제할까요?",
        ["Confirm.DeleteTagBody"] = "‘{0}’ 태그를 삭제해요. 계속할까요?",

        // Submodule / blame / rebase
        ["Submodule.Update"] = "서브모듈 업데이트",
        ["Submodule.Update.Tip"] = "서브모듈을 초기화하고 지정된 커밋으로 맞춰요.",
        ["Blame"] = "Blame (줄별 작성자)",
        ["Blame.Tip"] = "파일의 각 줄을 마지막으로 바꾼 커밋을 보여줘요.",
        ["FileHistory.Title"] = "파일 히스토리",
        ["FileHistory.Menu"] = "파일 히스토리 보기",
        ["Ctx.DeleteRemote"] = "원격 브랜치 삭제",
        ["Ctx.InteractiveRebase"] = "이 커밋 위로 대화형 리베이스",
        ["Rebase.NothingAbove"] = "이 커밋 위에 재배치할 커밋이 없어요.",

        // Commit details
        ["Details.Author"] = "작성자",
        ["Details.Date"] = "날짜",
        ["Details.Commit"] = "커밋",
        ["Details.Parents"] = "부모",
        ["Details.Message"] = "메시지",
        ["Details.ChangedFiles"] = "변경된 파일",
        ["Details.SelectCommit"] = "왼쪽에서 커밋을 선택하면 상세 내용이 보여요.",

        // Diff
        ["Diff.Binary"] = "바이너리 파일이라 변경 내용을 미리 볼 수 없어요.",
        ["Diff.TooLarge"] = "변경 내용이 너무 커서 미리보기를 생략했어요.",
        ["Diff.NoChanges"] = "표시할 변경이 없어요.",
        ["Diff.SelectFile"] = "파일을 선택하면 바뀐 줄이 색으로 표시돼요.",
        ["Diff.Split"] = "좌우 비교",
        ["Diff.SplitTip"] = "삭제된 줄과 추가된 줄을 왼쪽·오른쪽으로 나란히 비교해요.",
        ["Diff.PopOut"] = "새 창으로 열기",
        ["Diff.PopOut.Tip"] = "이 변경 내용을 별도 창으로 열어요. 창을 최대화하거나 F11로 전체화면을 쓸 수 있어요.",
        ["Diff.FullScreen"] = "⛶ 전체화면 (F11)",
        ["Diff.FullScreen.Tip"] = "전체화면으로 전환해요. F11 또는 Esc로 해제.",

        // Remote / status
        ["Remote.Ahead"] = "▲{0}",
        ["Remote.Behind"] = "▼{0}",
        ["Remote.AheadBehind.Tip"] = "원격보다 앞선 커밋 수(▲)와 뒤처진 커밋 수(▼)예요.",
        ["Status.NoRepo"] = "저장소를 열어 시작하세요",
        ["Status.Ready"] = "준비됨",
        ["Status.Loading"] = "불러오는 중…",
        ["Status.Working"] = "작업 중…",

        // Update
        ["Update.Available"] = "새 버전 {0} 이(가) 있어요",
        ["Update.Download"] = "다운로드 후 설치",
        ["Update.Later"] = "나중에",
        ["Update.UpToDate"] = "최신 버전을 쓰고 있어요",
        ["Update.Checking"] = "업데이트 확인 중…",
        ["Update.CheckFailed"] = "업데이트를 확인하지 못했어요",

        // Windows 탐색기 우클릭 통합 (TortoiseGit 대체)
        ["Shell.Menu.Root"] = "Git Tab",
        ["Shell.Menu.Open"] = "Git Tab에서 열기",
        ["Shell.Menu.Clone"] = "복제(Clone)…",
        ["Shell.Menu.Commit"] = "커밋…",
        ["Shell.Menu.Pull"] = "받아오기 (Pull)",
        ["Shell.Menu.Push"] = "올리기 (Push)",
        ["Shell.Menu.Fetch"] = "가져오기 (Fetch)",
        ["Shell.Menu.Stash"] = "변경 스태시",
        ["Shell.Menu.Log"] = "히스토리 / 로그",
        ["Shell.Tip"] = "Windows 탐색기에서 폴더를 우클릭하면 Git Tab 메뉴로 열기·커밋·풀·푸시를 바로 쓸 수 있어요. 체크 해제하면 제거돼요.",

        // GUI 인증 (자격 증명)
        ["Auth.Title"] = "Git 인증",
        ["Auth.Message"] = "‘{0}’에 접근하려면 로그인이 필요해요.",
        ["Auth.User"] = "사용자 이름",
        ["Auth.Secret"] = "비밀번호 · 액세스 토큰(PAT)",
        ["Auth.Hint"] = "GitHub·GitLab은 비밀번호 대신 개인 액세스 토큰(PAT)을 쓰세요. 입력한 정보는 Windows 자격 증명 관리자에 안전하게 저장되고 다음부터 자동으로 사용돼요.",
        ["Git.NotFound"] = "git 실행 파일을 찾지 못했어요. 히스토리 보기는 되지만 커밋·푸시 등에는 Git이 필요해요. https://git-scm.com/download/win 에서 설치하거나, Git Tab 설치본에 포함된 Git을 사용하세요.",

        // 설정 창
        ["Settings.Title"] = "설정",
        ["Settings.Appearance"] = "모양",
        ["Settings.Theme"] = "테마",
        ["Settings.ShellSection"] = "탐색기 통합",
        ["Settings.ShellEnable"] = "Windows 탐색기 우클릭 메뉴 사용",
        ["Settings.GitSection"] = "Git 실행 파일",
        ["Settings.AuthSection"] = "인증",
        ["Settings.ClearCred"] = "저장된 자격 증명 지우기",
        ["Settings.ClearCredTip"] = "현재 원격 저장소 호스트에 저장한 사용자 이름·토큰을 삭제해요. 다음 Push/Pull 때 다시 입력하게 돼요.",
        ["Settings.CredCleared"] = "저장된 자격 증명을 삭제했어요.",
        ["Settings.NoRemote"] = "삭제할 원격 자격 증명이 없어요.",
        ["Settings.Diagnostics"] = "진단",
        ["Settings.CrashReports"] = "오류 발생 시 크래시 리포트 저장",
        ["Settings.CrashReports.Tip"] = "예기치 못한 오류가 나면 자세한 리포트를 내 PC(%AppData%\\GitTab\\crashes)에 저장해요. 외부로 전송되지 않아요.",
        ["Settings.BackgroundFetch"] = "백그라운드에서 원격 자동 확인",
        ["Settings.BackgroundFetch.Tip"] = "몇 분마다 열려 있는 저장소를 조용히 fetch해서 '받아올 커밋 N개'를 최신으로 유지해요. 그래프는 그대로 두고 표시만 갱신해요.",
        ["Settings.BetaChannel"] = "베타 채널(미리보기 버전) 받기",
        ["Settings.BetaChannel.Tip"] = "업데이트 확인 시 정식 출시 전의 프리릴리스(베타)까지 포함해요. 새 기능을 먼저 써볼 수 있지만 불안정할 수 있어요.",
        ["Settings.Accessibility"] = "접근성",
        ["Settings.UiScale"] = "화면/글자 크기",
        ["Settings.UiScale.Tip"] = "제목 표시줄을 제외한 전체 화면을 확대해요(100~150%).",
        ["Settings.HighContrast"] = "고대비 테마",
        ["Settings.HighContrast.Tip"] = "검정 배경 + 흰 글자 + 선명한 강조색으로 대비를 높여 저시력 환경에서 보기 쉽게 해요.",
        ["Settings.OpenLogs"] = "로그 폴더 열기",
        ["Settings.About"] = "정보",

        // Advanced (Tier 1/2)
        ["Worktree.Manage"] = "워크트리 관리",
        ["Worktree.Tip"] = "한 저장소에서 여러 작업 폴더(워크트리)를 동시에 열어 브랜치별로 병행 작업할 수 있어요.",
        ["Worktree.Add"] = "워크트리 추가",
        ["Worktree.Prune"] = "정리(prune)",
        ["Worktree.RemoveConfirm"] = "‘{0}’ 워크트리를 제거할까요?",
        ["Worktree.PathPrompt"] = "새 워크트리를 만들 폴더 경로를 입력하세요",
        ["Worktree.BranchPrompt"] = "새로 만들 브랜치 이름 (비우면 현재 커밋 체크아웃)",
        ["Worktree.Current"] = "현재",
        ["Lfs.Manage"] = "Git LFS 관리",
        ["Lfs.Tip"] = "대용량 파일을 Git LFS로 추적하면 저장소가 가벼워져요.",
        ["Lfs.Track"] = "패턴 추적",
        ["Lfs.Pull"] = "LFS 받기(pull)",
        ["Lfs.PatternPrompt"] = "추적할 파일 패턴을 입력하세요 (예: *.psd)",
        ["Lfs.UntrackConfirm"] = "‘{0}’ 추적을 해제할까요?",
        ["Lfs.NotAvailable"] = "이 시스템에 git-lfs가 설치되어 있지 않아요.",
        ["Lfs.TrackedFiles"] = "추적 중인 파일 수:",
        ["Submodule.Manage"] = "서브모듈 관리",
        ["Submodule.Tip"] = "다른 저장소를 하위 폴더로 포함하는 서브모듈을 추가·동기화·업데이트해요.",
        ["Submodule.Add"] = "서브모듈 추가",
        ["Submodule.Sync"] = "URL 동기화",
        ["Submodule.Update"] = "업데이트(init)",
        ["Submodule.Deinit"] = "제거(deinit)",
        ["Submodule.UrlPrompt"] = "서브모듈 저장소 URL을 입력하세요",
        ["Submodule.PathPrompt"] = "서브모듈을 둘 하위 경로를 입력하세요",
        ["Submodule.DeinitConfirm"] = "‘{0}’ 서브모듈을 deinit 할까요?",
        ["Sparse.Manage"] = "스파스 체크아웃",
        ["Sparse.Tip"] = "대형 저장소에서 필요한 폴더만 작업 폴더에 두어 속도를 높여요.",
        ["Sparse.Add"] = "패턴 추가",
        ["Sparse.Disable"] = "해제",
        ["Sparse.DisableConfirm"] = "스파스 체크아웃을 해제하고 전체를 체크아웃할까요?",
        ["Sparse.PatternPrompt"] = "포함할 폴더/패턴을 입력하세요 (예: src)",
        ["Sparse.Cone"] = "cone 모드 (폴더 단위, 권장)",
        ["Cred.Manage"] = "저장된 자격증명",
        ["Cred.Tip"] = "Git Tab이 Windows 자격증명 관리자에 저장한 인증 정보(PAT)를 보고 삭제할 수 있어요.",
        ["Cred.DeleteConfirm"] = "‘{0}’ 자격증명을 삭제할까요?",
        ["Cred.Empty"] = "저장된 자격증명이 없어요.",
        ["Sign.Verified"] = "서명 확인됨",
        ["Sign.Untrusted"] = "서명됨 (신뢰 안 됨)",
        ["Sign.Bad"] = "서명 오류",
        ["Sign.None"] = "서명 없음",
        ["Sign.Unknown"] = "서명 확인 불가",
        ["Commit.Sign"] = "커밋 서명 (GPG/SSH)",
        ["Settings.Signing"] = "커밋 서명",
        ["Settings.Signing.Tip"] = "새 커밋을 GPG 또는 SSH 키로 서명해요. 키와 형식은 git 설정을 따라요.",
        ["Settings.Signing.Enable"] = "이 저장소에서 커밋 서명 사용",
        ["Ctx.ExportPatch"] = "패치로 내보내기 (.patch)",
        ["Patch.Apply"] = "패치 적용…",
        ["Patch.ExportTitle"] = "커밋을 패치로 저장",
        ["Patch.ApplyTitle"] = "패치 파일 적용",
        ["Patch.AsCommits"] = "커밋으로 적용 (git am)",
        ["Ctx.StashDiff"] = "변경 내용 미리보기",
        ["Ctx.StashToBranch"] = "브랜치로 만들기",
        ["Stash.ToBranchPrompt"] = "새 브랜치 이름을 입력하세요",
        ["Stash.DiffTitle"] = "스태시 변경 내용",
        ["GraphSearch.Placeholder"] = "그래프 검색 (메시지·작성자·SHA)",
        ["GraphSearch.NoMatch"] = "일치하는 커밋이 없어요",
        ["HunkStage.StageLines"] = "선택한 줄 스테이지",
        ["HunkStage.LineHint"] = "스테이지할 줄을 선택하세요 (+/− 줄만).",
        ["Clone.Blobless"] = "부분 복제 (blobless — 대형 저장소에 빠름)",
        ["Tab.Close"] = "탭 닫기",
        ["WC.SignOff"] = "Sign-off 추가 (-s)",
        ["CoAuthor.Add"] = "공동 작성자 추가",
        ["CoAuthor.Title"] = "공동 작성자 (Co-authored-by)",
        ["CoAuthor.NamePrompt"] = "공동 작성자 이름을 입력하세요",
        ["CoAuthor.EmailPrompt"] = "공동 작성자 이메일을 입력하세요",
        ["Push.Force"] = "강제 푸시 (--force-with-lease)",
        ["Push.ForceConfirm"] = "원격 히스토리를 덮어씁니다. --force-with-lease로 안전하게(원격이 바뀌었으면 거부) 푸시할까요?",
        ["Author.Amend"] = "작성자 수정",
        ["Author.NamePrompt"] = "작성자 이름",
        ["Author.EmailPrompt"] = "작성자 이메일",
        ["Restore.Title"] = "파일 되돌리기",
        ["Restore.Confirm"] = "‘{0}’을(를) 커밋 {1}의 내용으로 되돌릴까요? 작업 폴더의 현재 내용은 덮어써집니다.",
        ["Ctx.RestoreFile"] = "이 버전으로 파일 되돌리기",
        ["Ctx.AmendAuthor"] = "작성자 수정 (마지막 커밋)",
        ["Ctx.AddToGitignore"] = ".gitignore에 추가",
        ["Menu.Statistics"] = "저장소 통계…",
        ["Menu.Config"] = "Git 설정 편집…",
        ["Menu.Bookmarks"] = "북마크",
        ["Ctx.Bookmark"] = "북마크 토글 (★)",
        ["Menu.Changelog"] = "CHANGELOG 생성…",
        ["Changelog.Title"] = "CHANGELOG 생성",
        ["Changelog.From"] = "시작 지점:",
        ["Changelog.Generate"] = "생성",
        ["Changelog.Copy"] = "복사",
        ["Changelog.Save"] = "저장…",
        ["Changelog.SaveTitle"] = "CHANGELOG 저장",
        ["Changelog.AllHistory"] = "(전체 히스토리)",
        ["Menu.ForcePush"] = "강제 푸시 (--force-with-lease)",
        ["Stats.Title"] = "저장소 통계",
        ["Stats.Commits"] = "커밋",
        ["Stats.Branches"] = "브랜치",
        ["Stats.Tags"] = "태그",
        ["Stats.LastActivity"] = "마지막 활동",
        ["Stats.Contributors"] = "기여자",
        ["Stats.Loading"] = "불러오는 중…",
        ["Config.Title"] = "Git 설정",
        ["Config.Tip"] = "이름·이메일 등 Git 설정을 편집해요. ‘전체 적용’을 켜면 모든 저장소에 적용됩니다(--global).",
        ["Config.UserName"] = "이름 (user.name)",
        ["Config.UserEmail"] = "이메일 (user.email)",
        ["Config.Local"] = "이 저장소",
        ["Config.Global"] = "전체 적용 (--global)",
        ["Config.SetCustom"] = "다른 키 설정…",
        ["Config.KeyPrompt"] = "설정 키를 입력하세요 (예: core.editor)",
        ["Config.ValuePrompt"] = "값을 입력하세요",
        ["Common.Save"] = "저장",
        ["Menu.Hosting"] = "PR·이슈 (GitHub/GitLab)…",
        ["Menu.OpenInEditor"] = "에디터에서 열기 (VS Code)",
        ["Ctx.OpenInEditor"] = "에디터에서 열기",
        ["Ctx.ExternalDiff"] = "외부 diff 도구로 열기",
        ["Hosting.Title"] = "Pull Request · 이슈",
        ["Hosting.PullRequests"] = "Pull Request",
        ["Hosting.Issues"] = "이슈",
        ["Hosting.Loading"] = "불러오는 중…",
        ["Hosting.Empty"] = "열린 PR이나 이슈가 없어요. (원격 호스트 지원·토큰 필요)",
        ["Hosting.Open"] = "열기",
        ["Hosting.Comments"] = "댓글",
        ["Hosting.CommentsSelectPrompt"] = "PR이나 이슈를 선택하면 댓글을 볼 수 있어요.",
        ["Hosting.CommentsLoading"] = "댓글 불러오는 중…",
        ["Hosting.CommentsEmpty"] = "아직 댓글이 없어요.",
        ["Hosting.NewComment"] = "새 댓글",
        ["Hosting.PostComment"] = "댓글 등록",
        ["Hosting.Posting"] = "등록하는 중…",
        ["Hosting.CommentPosted"] = "댓글을 등록했어요.",
        ["Hosting.CommentPostFailed"] = "댓글 등록에 실패했어요. 토큰에 쓰기 권한이 있는지 확인하세요.",
        ["CI.Success"] = "CI 통과",
        ["CI.Pending"] = "CI 진행 중",
        ["CI.Failure"] = "CI 실패",
        ["Auth.DeviceTitle"] = "GitHub 로그인",
        ["Auth.DeviceNotConfigured"] = "OAuth 기기 로그인은 등록된 GitHub OAuth 앱 client_id가 필요해요. 현재는 PAT(개인 접근 토큰)로 인증합니다.",
        ["Branch.PruneMerged"] = "병합된 브랜치 정리",
        ["Branch.PruneMerged.Tip"] = "현재 브랜치에 이미 병합된 로컬 브랜치들을 정리해요 (main/master/develop 제외).",
        ["Branch.PruneConfirm"] = "다음 브랜치를 삭제할까요? {0}",
        ["Branch.NoStale"] = "정리할 병합된 브랜치가 없어요.",
        ["Diff.IgnoreWhitespace"] = "공백 무시",
        ["Diff.ExpandContext"] = "＋문맥",
        ["Diff.ExpandContext.Tip"] = "변경 주변에 보이는 줄(문맥)을 더 표시해요.",
        ["Diff.ShrinkContext"] = "－문맥",
        ["Diff.ShrinkContext.Tip"] = "문맥 줄 수를 기본값으로 줄여요.",
        ["Diff.ImageOld"] = "이전",
        ["Diff.ImageNew"] = "현재",
        ["Menu.Advanced"] = "고급",
        ["Menu.Tools"] = "도구",
        ["Menu.Tools.Tip"] = "더 많은 작업 (reflog·비교·검색·원격·워크트리·LFS 등)",
        ["Menu.Worktrees"] = "워크트리…",
        ["Menu.Lfs"] = "Git LFS…",
        ["Menu.Submodules"] = "서브모듈…",
        ["Menu.Sparse"] = "스파스 체크아웃…",
        ["Menu.Credentials"] = "저장된 자격증명…",
        ["Menu.Keybindings"] = "키보드 단축키…",

        // 키보드 단축키 (Keybindings dialog)
        ["Keybind.Title"] = "키보드 단축키",
        ["Keybind.Tip"] = "각 작업의 단축키를 확인하고 원하는 대로 바꿀 수 있어요. 두 작업이 같은 키를 쓰면 아래에서 붉게 표시돼요.",
        ["Keybind.Col.Action"] = "작업",
        ["Keybind.Col.Shortcut"] = "단축키",
        ["Keybind.Rebind"] = "다시 지정",
        ["Keybind.PressKey"] = "키를 누르세요…",
        ["Keybind.Reset"] = "초기화",
        ["Keybind.ResetAll"] = "모두 초기화",
        ["Keybind.Customized"] = "(변경됨)",
        ["Keybind.Conflict"] = "다른 작업과 단축키가 겹쳐요",
        ["Keybind.ConflictBanner"] = "일부 단축키가 서로 겹쳐요. 겹치는 작업은 하나만 실행될 수 있으니 아래에서 다시 지정하세요.",
        ["Keybind.Action.OpenRepository"] = "저장소 열기",
        ["Keybind.Action.CreateRepository"] = "저장소 만들기",
        ["Keybind.Action.CommandPalette"] = "명령 팔레트 열기",
        ["Keybind.Action.FocusSearch"] = "검색창으로 이동",
        ["Keybind.Action.CloseTab"] = "탭 닫기",
        ["Keybind.Action.NextTab"] = "다음 탭",
        ["Keybind.Action.PreviousTab"] = "이전 탭",
        ["Keybind.Action.Refresh"] = "새로고침",
        ["Keybind.Action.Fetch"] = "가져오기",
        ["Keybind.Action.Commit"] = "커밋하기",

        // Common / dialogs
        ["Common.OK"] = "확인",
        ["Common.Cancel"] = "취소",
        ["Common.Yes"] = "예",
        ["Common.No"] = "아니오",
        ["Common.Close"] = "닫기",
        ["Common.Error"] = "오류",
        ["Common.Warning"] = "주의",
        ["Common.Success"] = "완료",
        ["Common.Delete"] = "삭제",
        ["Confirm.DiscardTitle"] = "변경을 되돌릴까요?",
        ["Confirm.DiscardBody"] = "‘{0}’의 수정 내용이 사라지고 복구할 수 없어요. 계속할까요?",
        ["Confirm.DeleteBranchTitle"] = "브랜치를 삭제할까요?",
        ["Confirm.DeleteBranchBody"] = "‘{0}’ 브랜치를 삭제해요. 계속할까요?",
        ["Error.OpenFailed"] = "저장소를 열 수 없어요",
        ["Error.GitFailed"] = "Git 명령이 실패했어요",
        ["Error.NotARepo"] = "선택한 폴더는 Git 저장소가 아니에요.",

        // Relative time
        ["Time.JustNow"] = "방금 전",
        ["Time.MinutesAgo"] = "{0}분 전",
        ["Time.HoursAgo"] = "{0}시간 전",
        ["Time.DaysAgo"] = "{0}일 전",
        ["Time.MonthsAgo"] = "{0}개월 전",
        ["Time.YearsAgo"] = "{0}년 전",
    };

    private static readonly Dictionary<string, string> En = new(StringComparer.Ordinal)
    {
        ["App.Title"] = "Git Tab",

        ["Action.Open"] = "Open repository",
        ["Action.Open.Tip"] = "Pick a Git repository folder on your computer to open.",
        ["Action.Refresh"] = "Refresh",
        ["Action.Refresh.Tip"] = "Re-read the repository's latest state.",
        ["Undo.Title"] = "Undo",
        ["Undo.Tip"] = "Undo the last Git action (via the reflog). Undoing a commit keeps your changes staged; anything else restores the previous state. Uncommitted local changes are protected.",
        ["Undo.Confirm"] = "Undo the last action?\n\nAction: {0}\n\nThis restores the previous state. (Undoing a commit/amend keeps your changes staged.)",
        ["Action.Recent"] = "Recent",
        ["Action.Recent.Empty"] = "No recent repositories",
        ["Action.Fetch"] = "Fetch",
        ["Action.Fetch.Tip"] = "Downloads the latest commit info from the remote. It does NOT change your files or branches — safe to click anytime.",
        ["Action.Pull"] = "Pull",
        ["Action.Pull.Tip"] = "Fetches remote changes and merges them into your current branch (fetch + merge).",
        ["Action.Push"] = "Push",
        ["Action.Push.Tip"] = "Sends your commits to the remote. Authentication is handled by your system Git credential helper.",
        ["Action.Commit"] = "Commit",

        // Clone
        ["Clone.Title"] = "Clone repository",
        ["Clone.Action"] = "Clone",
        ["Clone.Tip"] = "Copy a remote repository to your computer from its URL.",
        ["Clone.Url"] = "Remote URL",
        ["Clone.Parent"] = "Clone into (parent folder)",
        ["Clone.FolderName"] = "Folder name",

        // Create repository / remotes
        ["Repo.Create"] = "Create repository",
        ["Repo.Create.Tip"] = "Pick a folder to create a new Git repository (git init). You can also wire up a remote URL.",
        ["Repo.Create.Tip.Short"] = "Create a new Git repository.",
        ["Repo.Folder"] = "Folder",
        ["Repo.Browse"] = "Browse…",
        ["Repo.InitialBranch"] = "Initial branch name",
        ["Repo.RemoteOptional"] = "Remote URL (optional)",
        ["Repo.Remote.Tip"] = "e.g. https://github.com/user/repo.git — leave empty to add it later under \"Remotes\".",
        ["Remote.Button"] = "Remotes",
        ["Remote.Manage"] = "Manage remotes",
        ["Remote.Tip"] = "Add, change, or remove remote (e.g. origin) URLs — where Push/Pull go.",
        ["Remote.Add"] = "Add remote",
        ["Remote.Edit"] = "Change URL",
        ["Remote.EditUrl"] = "Change URL",
        ["Remote.Remove"] = "Remove remote",
        ["Remote.NamePrompt"] = "Enter the remote name (usually origin)",
        ["Remote.UrlPrompt"] = "Enter the remote repository URL",
        ["Remote.RemoveConfirm"] = "Remove the remote '{0}'? (Your local commits are kept.)",

        // Hosting integration (GitHub/GitLab)
        ["Hosting.PR"] = "New PR",
        ["Hosting.PR.Tip"] = "Open the GitHub Pull Request / GitLab Merge Request page for the current branch in your browser.",
        ["Hosting.Web"] = "Open on web",
        ["Hosting.Web.Tip"] = "Open this repository's remote web page (GitHub/GitLab, etc.) in your browser.",
        ["Hosting.Unsupported"] = "This remote doesn't support opening a PR page (GitHub/GitLab only). Make sure a remote is set and you've pushed the branch.",
        ["Hosting.NoRemote"] = "No remote web URL to open.",

        // History / undo (reflog)
        ["Reflog.Title"] = "History & undo",
        ["Reflog.Tip"] = "Recent positions HEAD has been at. If a commit, merge, or reset went wrong, you can restore from here.",
        ["Reflog.Reset"] = "Restore",
        ["Reflog.ResetConfirm"] = "Restore to '{0}'? (reset --hard — unsaved changes will be lost.)",
        ["Reflog.UndoLast"] = "↩ Undo last action",
        ["Reflog.UndoLast.Tip"] = "Restore the previous state (HEAD@{1}) — handy for undoing what you just did.",

        ["Language"] = "Language",
        ["Language.Korean"] = "한국어",
        ["Language.English"] = "English",
        ["Settings"] = "Settings",
        ["Theme.Toggle"] = "Toggle theme",
        ["Theme.Pick"] = "Choose theme",
        ["Theme.Light"] = "Light",
        ["Theme.Dark"] = "Dark",
        ["Search.Placeholder"] = "Search message · author · hash",
        ["Search.Tip"] = "Filter commits by message text, author name, or commit hash.",
        ["Palette.Placeholder"] = "Search commands… (Ctrl+P)",
        ["Compare.Title"] = "Compare branches/commits",
        ["Compare.Tip"] = "Compare changed files and diffs between two branches, tags, or commits.",
        ["Compare.From"] = "Base",
        ["Compare.To"] = "Target",
        ["Compare.Changed"] = "Changed files",
        ["Search.Content"] = "Content search",
        ["Search.Content.Tip"] = "Find commits that added or removed a string in the code (pickaxe). Regex supported.",
        ["Search.Regex"] = "Regex",
        ["Search.Run"] = "Search",
        ["Search.Empty"] = "No matching commits.",
        ["Search.DblClick"] = "Double-click a result to jump to that commit.",
        ["Search.NotInView"] = "That commit isn't in the current list.",

        ["Panel.History"] = "History",
        ["Panel.Changes"] = "Changes",
        ["Panel.Branches"] = "Branches",
        ["Panel.Details"] = "Commit details",
        ["Panel.Diff"] = "Diff",

        ["Col.Refs"] = "BRANCH / TAG",
        ["Col.Graph"] = "GRAPH",
        ["Col.Message"] = "COMMIT MESSAGE",
        ["Col.Changes"] = "CHANGES",
        ["Col.Author"] = "AUTHOR",
        ["Col.Date"] = "COMMIT DATE",
        ["Col.Sha"] = "SHA",

        ["Welcome.Title"] = "Welcome to Git Tab",
        ["Welcome.Subtitle"] = "Open a repository folder, or drag a folder onto this window.",
        ["Welcome.Open"] = "Open repository",
        ["Welcome.Hint"] = "New to Git? Hover any button to see what it does.",

        ["WC.Staged"] = "Staged (will be in the next commit)",
        ["WC.Unstaged"] = "Unstaged (not in the commit yet)",
        ["WC.StageAll"] = "Stage all",
        ["WC.StageAll.Tip"] = "Add all changes to the next commit.",
        ["WC.UnstageAll"] = "Unstage all",
        ["WC.Stage.Tip"] = "Add this file's changes to the next commit.",
        ["WC.StagePartial"] = "Stage parts",
        ["WC.StagePartial.Tip"] = "Stage only selected changed blocks (hunks) instead of the whole file. (git add -p)",
        ["WC.StagePartial.StageHunk"] = "Stage this hunk",
        ["WC.StagePartial.Empty"] = "Nothing to stage by hunk. (Use + to stage a whole new file.)",
        ["WC.Unstage.Tip"] = "Remove this file from the next commit (your edits stay).",
        ["WC.Discard"] = "Discard changes",
        ["WC.Discard.Tip"] = "Throw away this file's edits and restore it to the last commit. ⚠ This can't be undone.",
        ["WC.Type"] = "Type",
        ["WC.Type.Tip"] = "Pick a commit type to auto-prefix the message (e.g. 'feat:', 'fix:') — Conventional Commits made easy.",
        ["WC.CommitMessage.Placeholder"] = "Describe what changed and why",
        ["WC.Amend"] = "Amend last commit",
        ["WC.Amend.Tip"] = "Instead of a new commit, fold these changes into your most recent commit (or edit its message).",
        ["WC.Commit"] = "Commit",
        ["WC.Commit.Tip"] = "Save your staged changes as one commit (a snapshot). A commit is a safe point you can always return to.",
        ["WC.NothingToCommit"] = "Nothing to commit",
        ["WC.Clean"] = "No changes — your working tree is clean!",

        ["Branch.Local"] = "Local branches",
        ["Branch.Remote"] = "Remote branches",
        ["Branch.Checkout"] = "Switch to this branch",
        ["Branch.Checkout.Tip"] = "Switch to this branch; your working files change to match it.",
        ["Branch.New"] = "New branch",
        ["Branch.New.Tip"] = "Create a new branch from where you are. A branch is a parallel space to experiment safely.",
        ["Branch.Delete"] = "Delete branch",
        ["Branch.Delete.Tip"] = "Delete this branch. You'll be warned if it has unmerged commits.",
        ["Branch.Rename"] = "Rename",
        ["Branch.Rename.Tip"] = "Rename this branch.",
        ["Branch.Merge"] = "Merge into current",
        ["Branch.Merge.Tip"] = "Combine the selected branch's changes into your current branch.",
        ["Branch.Rebase"] = "Rebase",
        ["Branch.Rebase.Tip"] = "Re-apply your current branch's commits on top of the selected branch. This rewrites history — use with care.",
        ["Branch.NewName.Prompt"] = "Enter a name for the new branch",
        ["Branch.RenamePrompt"] = "Enter the new name",

        ["Ctx.CheckoutCommit"] = "Checkout this commit (detached)",
        ["Ctx.Reword"] = "Reword message",
        ["Reword.Title"] = "Reword commit message",
        ["Reword.Prompt"] = "Enter the new commit message. (If it isn't the latest commit, the commits above it are rewritten.)",
        ["Ctx.CreateBranch"] = "Create branch here",
        ["Ctx.CreateTag"] = "Create tag here",
        ["Ctx.ResetSoft"] = "Reset here — soft (keep changes)",
        ["Ctx.ResetMixed"] = "Reset here — mixed (unstage)",
        ["Ctx.ResetHard"] = "Reset here — hard ⚠ (discard changes)",
        ["Ctx.Revert"] = "Revert this commit",
        ["Ctx.CherryPick"] = "Cherry-pick this commit",
        ["Ctx.CopySha"] = "Copy commit hash (SHA)",
        ["Ctx.CopyMessage"] = "Copy commit message",
        ["Ctx.OpenFile"] = "Open file",
        ["Ctx.CopyPath"] = "Copy path",

        ["Gitignore.Button"] = ".gitignore",
        ["Gitignore.Title"] = "Create .gitignore",
        ["Gitignore.Tip"] = "Detects your project's stack and generates a matching .gitignore, so build output, caches, and other noise stay out of version control.",
        ["Gitignore.Detected"] = "Stacks to include (detected ones are pre-selected)",
        ["Gitignore.Write"] = "Create / overwrite",
        ["Gitignore.Append"] = "Append to existing",
        ["Gitignore.Exists"] = "A .gitignore already exists.",

        ["State.Merge"] = "Merging",
        ["State.Rebase"] = "Rebasing",
        ["State.CherryPick"] = "Cherry-picking",
        ["State.Revert"] = "Reverting",
        ["State.Bisect"] = "Bisecting",
        ["Ctx.StartBisect"] = "Bisect from here (this commit is good)",
        ["Bisect.Title"] = "Bisect",
        ["Bisect.StartConfirm"] = "Start bisect with this commit as 'good' and current HEAD as 'bad'? A midpoint commit will be checked out.",
        ["Bisect.Good"] = "Good ✓",
        ["Bisect.Good.Tip"] = "The currently checked-out commit is fine.",
        ["Bisect.Bad"] = "Bad ✗",
        ["Bisect.Bad.Tip"] = "The currently checked-out commit has the problem.",
        ["Bisect.Skip"] = "Skip",
        ["Bisect.Reset"] = "End",
        ["Conflict.Hint"] = "Resolve the conflicted files (stage with ＋), then Continue — or Abort to cancel.",
        ["Conflict.Continue"] = "Continue",
        ["Conflict.Abort"] = "Abort",
        ["Conflict.Resolve"] = "Resolve conflict",
        ["Conflict.ResolveHint"] = "For each conflict, choose which side to keep. Applying writes the file and marks it resolved (staged).",
        ["Conflict.UseOurs"] = "Ours",
        ["Conflict.UseTheirs"] = "Theirs",
        ["Conflict.Both"] = "Both",
        ["Conflict.Ours"] = "Ours (yours)",
        ["Conflict.Theirs"] = "Theirs (incoming)",
        ["Conflict.Base"] = "Common ancestor (base)",
        ["Conflict.NoBase"] = "(no common ancestor — new file or merge base unavailable)",
        ["Conflict.Result"] = "Final result (edit directly)",
        ["Conflict.UseOursAll"] = "Use ours",
        ["Conflict.UseTheirsAll"] = "Use theirs",
        ["Conflict.KeepBoth"] = "Keep both (strip markers)",
        ["Conflict.ApplyResolve"] = "Apply resolution",

        ["Stash.Section"] = "Stashes",
        ["Stash.Push"] = "Stash changes",
        ["Stash.Push.Tip"] = "Set your current changes aside so the working tree is clean; restore them later.",
        ["Stash.Pop"] = "Apply & drop (pop)",
        ["Stash.Apply"] = "Apply",
        ["Stash.Drop"] = "Drop",
        ["Stash.Empty"] = "No stashes",

        ["Tag.Section"] = "Tags",
        ["Tag.Push"] = "Push to remote",
        ["Tag.Delete"] = "Delete tag",
        ["Confirm.DeleteTagTitle"] = "Delete tag?",
        ["Confirm.DeleteTagBody"] = "The tag '{0}' will be deleted. Continue?",

        ["Submodule.Update"] = "Update submodules",
        ["Submodule.Update.Tip"] = "Initialize submodules and check out their pinned commits.",
        ["Blame"] = "Blame (per-line authorship)",
        ["Blame.Tip"] = "Show which commit last changed each line of the file.",
        ["FileHistory.Title"] = "File history",
        ["FileHistory.Menu"] = "View file history",
        ["Ctx.DeleteRemote"] = "Delete remote branch",
        ["Ctx.InteractiveRebase"] = "Interactive rebase onto this commit",
        ["Rebase.NothingAbove"] = "No commits above this one to rebase.",

        ["Details.Author"] = "Author",
        ["Details.Date"] = "Date",
        ["Details.Commit"] = "Commit",
        ["Details.Parents"] = "Parents",
        ["Details.Message"] = "Message",
        ["Details.ChangedFiles"] = "Changed files",
        ["Details.SelectCommit"] = "Select a commit on the left to see its details.",

        ["Diff.Binary"] = "Binary file — no preview available.",
        ["Diff.TooLarge"] = "Change is too large — preview skipped.",
        ["Diff.NoChanges"] = "No changes to show.",
        ["Diff.SelectFile"] = "Select a file to see changed lines highlighted.",
        ["Diff.Split"] = "Split",
        ["Diff.SplitTip"] = "Compare removed and added lines side by side.",
        ["Diff.PopOut"] = "Open in new window",
        ["Diff.PopOut.Tip"] = "Open this diff in its own window — maximize it, or press F11 for fullscreen.",
        ["Diff.FullScreen"] = "⛶ Fullscreen (F11)",
        ["Diff.FullScreen.Tip"] = "Toggle fullscreen. Press F11 or Esc to exit.",

        ["Remote.Ahead"] = "▲{0}",
        ["Remote.Behind"] = "▼{0}",
        ["Remote.AheadBehind.Tip"] = "Commits you are ahead of the remote (▲) and behind it (▼).",
        ["Status.NoRepo"] = "Open a repository to begin",
        ["Status.Ready"] = "Ready",
        ["Status.Loading"] = "Loading…",
        ["Status.Working"] = "Working…",

        ["Update.Available"] = "Version {0} is available",
        ["Update.Download"] = "Download & install",
        ["Update.Later"] = "Later",
        ["Update.UpToDate"] = "You're on the latest version",
        ["Update.Checking"] = "Checking for updates…",
        ["Update.CheckFailed"] = "Couldn't check for updates",

        // Windows Explorer right-click integration (TortoiseGit replacement)
        ["Shell.Menu.Root"] = "Git Tab",
        ["Shell.Menu.Open"] = "Open in Git Tab",
        ["Shell.Menu.Clone"] = "Clone…",
        ["Shell.Menu.Commit"] = "Commit…",
        ["Shell.Menu.Pull"] = "Pull",
        ["Shell.Menu.Push"] = "Push",
        ["Shell.Menu.Fetch"] = "Fetch",
        ["Shell.Menu.Stash"] = "Stash changes",
        ["Shell.Menu.Log"] = "History / Log",
        ["Shell.Tip"] = "Right-click any folder in Windows Explorer to open, commit, pull or push with Git Tab. Uncheck to remove.",

        // GUI authentication (credentials)
        ["Auth.Title"] = "Git authentication",
        ["Auth.Message"] = "Sign in to access '{0}'.",
        ["Auth.User"] = "Username",
        ["Auth.Secret"] = "Password · Access token (PAT)",
        ["Auth.Hint"] = "For GitHub/GitLab use a Personal Access Token (PAT) instead of your password. Your details are saved securely in Windows Credential Manager and reused automatically.",
        ["Git.NotFound"] = "No git executable was found. Viewing history works, but commit/push need Git. Install it from https://git-scm.com/download/win, or use the Git bundled with the Git Tab installer.",

        // Settings window
        ["Settings.Title"] = "Settings",
        ["Settings.Appearance"] = "Appearance",
        ["Settings.Theme"] = "Theme",
        ["Settings.ShellSection"] = "Explorer integration",
        ["Settings.ShellEnable"] = "Windows Explorer right-click menu",
        ["Settings.GitSection"] = "Git executable",
        ["Settings.AuthSection"] = "Authentication",
        ["Settings.ClearCred"] = "Clear saved credentials",
        ["Settings.ClearCredTip"] = "Remove the username/token saved for the current remote's host. You'll be asked again on the next push/pull.",
        ["Settings.CredCleared"] = "Saved credentials were cleared.",
        ["Settings.NoRemote"] = "No remote credentials to clear.",
        ["Settings.Diagnostics"] = "Diagnostics",
        ["Settings.CrashReports"] = "Save a crash report on unexpected errors",
        ["Settings.CrashReports.Tip"] = "Writes a detailed report to your PC (%AppData%\\GitTab\\crashes) when something goes wrong. Nothing is uploaded.",
        ["Settings.BackgroundFetch"] = "Check remotes automatically in the background",
        ["Settings.BackgroundFetch.Tip"] = "Quietly fetches open repositories every few minutes to keep the \"N to pull\" count current. The graph stays put — only the indicator updates.",
        ["Settings.BetaChannel"] = "Get beta (preview) releases",
        ["Settings.BetaChannel.Tip"] = "When checking for updates, include pre-release (beta) builds published before the stable release. You get new features earlier, but they may be less stable.",
        ["Settings.Accessibility"] = "Accessibility",
        ["Settings.UiScale"] = "UI / text size",
        ["Settings.UiScale.Tip"] = "Zooms the whole window (title bar excluded), from 100% to 150%.",
        ["Settings.HighContrast"] = "High-contrast theme",
        ["Settings.HighContrast.Tip"] = "Black background, white text and a vivid accent for stronger contrast — easier to read for low vision.",
        ["Settings.OpenLogs"] = "Open logs folder",
        ["Settings.About"] = "About",

        // Advanced (Tier 1/2)
        ["Worktree.Manage"] = "Manage worktrees",
        ["Worktree.Tip"] = "Open several working folders (worktrees) from one repository to work on branches side by side.",
        ["Worktree.Add"] = "Add worktree",
        ["Worktree.Prune"] = "Prune",
        ["Worktree.RemoveConfirm"] = "Remove the worktree at '{0}'?",
        ["Worktree.PathPrompt"] = "Folder path for the new worktree",
        ["Worktree.BranchPrompt"] = "New branch name (leave blank to check out the current commit)",
        ["Worktree.Current"] = "current",
        ["Lfs.Manage"] = "Manage Git LFS",
        ["Lfs.Tip"] = "Track large files with Git LFS to keep the repository lightweight.",
        ["Lfs.Track"] = "Track pattern",
        ["Lfs.Pull"] = "LFS pull",
        ["Lfs.PatternPrompt"] = "File pattern to track (e.g. *.psd)",
        ["Lfs.UntrackConfirm"] = "Stop tracking '{0}'?",
        ["Lfs.NotAvailable"] = "git-lfs is not installed on this system.",
        ["Lfs.TrackedFiles"] = "Tracked files:",
        ["Submodule.Manage"] = "Manage submodules",
        ["Submodule.Tip"] = "Add, sync, and update submodules — other repositories nested as sub-folders.",
        ["Submodule.Add"] = "Add submodule",
        ["Submodule.Sync"] = "Sync URLs",
        ["Submodule.Update"] = "Update (init)",
        ["Submodule.Deinit"] = "Deinit",
        ["Submodule.UrlPrompt"] = "Submodule repository URL",
        ["Submodule.PathPrompt"] = "Sub-folder path for the submodule",
        ["Submodule.DeinitConfirm"] = "Deinit the submodule at '{0}'?",
        ["Sparse.Manage"] = "Sparse checkout",
        ["Sparse.Tip"] = "Keep only the folders you need in the working tree — faster on large repositories.",
        ["Sparse.Add"] = "Add pattern",
        ["Sparse.Disable"] = "Disable",
        ["Sparse.DisableConfirm"] = "Disable sparse checkout and check out everything?",
        ["Sparse.PatternPrompt"] = "Folder/pattern to include (e.g. src)",
        ["Sparse.Cone"] = "cone mode (by folder, recommended)",
        ["Cred.Manage"] = "Saved credentials",
        ["Cred.Tip"] = "View and delete the credentials (PATs) Git Tab saved in Windows Credential Manager.",
        ["Cred.DeleteConfirm"] = "Delete the credential for '{0}'?",
        ["Cred.Empty"] = "No saved credentials.",
        ["Sign.Verified"] = "Signature verified",
        ["Sign.Untrusted"] = "Signed (untrusted)",
        ["Sign.Bad"] = "Bad signature",
        ["Sign.None"] = "Not signed",
        ["Sign.Unknown"] = "Signature unverifiable",
        ["Commit.Sign"] = "Sign commit (GPG/SSH)",
        ["Settings.Signing"] = "Commit signing",
        ["Settings.Signing.Tip"] = "Sign new commits with a GPG or SSH key. The key and format follow your git config.",
        ["Settings.Signing.Enable"] = "Sign commits in this repository",
        ["Ctx.ExportPatch"] = "Export as patch (.patch)",
        ["Patch.Apply"] = "Apply patch…",
        ["Patch.ExportTitle"] = "Save commit as patch",
        ["Patch.ApplyTitle"] = "Apply patch file",
        ["Patch.AsCommits"] = "Apply as commits (git am)",
        ["Ctx.StashDiff"] = "Preview changes",
        ["Ctx.StashToBranch"] = "Create branch from stash",
        ["Stash.ToBranchPrompt"] = "New branch name",
        ["Stash.DiffTitle"] = "Stash changes",
        ["GraphSearch.Placeholder"] = "Search graph (message · author · SHA)",
        ["GraphSearch.NoMatch"] = "No matching commit",
        ["HunkStage.StageLines"] = "Stage selected lines",
        ["HunkStage.LineHint"] = "Select the lines to stage (+/− lines only).",
        ["Clone.Blobless"] = "Partial clone (blobless — faster for large repos)",
        ["Tab.Close"] = "Close tab",
        ["WC.SignOff"] = "Add Sign-off (-s)",
        ["CoAuthor.Add"] = "Add co-author",
        ["CoAuthor.Title"] = "Co-author (Co-authored-by)",
        ["CoAuthor.NamePrompt"] = "Co-author's name",
        ["CoAuthor.EmailPrompt"] = "Co-author's email",
        ["Push.Force"] = "Force push (--force-with-lease)",
        ["Push.ForceConfirm"] = "This overwrites remote history. Push with --force-with-lease (refuses if the remote moved)?",
        ["Author.Amend"] = "Edit author",
        ["Author.NamePrompt"] = "Author name",
        ["Author.EmailPrompt"] = "Author email",
        ["Restore.Title"] = "Restore file",
        ["Restore.Confirm"] = "Restore '{0}' to its content at commit {1}? Your current working copy of it is overwritten.",
        ["Ctx.RestoreFile"] = "Restore file to this version",
        ["Ctx.AmendAuthor"] = "Edit author (last commit)",
        ["Ctx.AddToGitignore"] = "Add to .gitignore",
        ["Menu.Statistics"] = "Repository statistics…",
        ["Menu.Config"] = "Edit Git config…",
        ["Menu.Bookmarks"] = "Bookmarks",
        ["Ctx.Bookmark"] = "Toggle bookmark (★)",
        ["Menu.Changelog"] = "Generate CHANGELOG…",
        ["Changelog.Title"] = "Generate CHANGELOG",
        ["Changelog.From"] = "From:",
        ["Changelog.Generate"] = "Generate",
        ["Changelog.Copy"] = "Copy",
        ["Changelog.Save"] = "Save…",
        ["Changelog.SaveTitle"] = "Save CHANGELOG",
        ["Changelog.AllHistory"] = "(all history)",
        ["Menu.ForcePush"] = "Force push (--force-with-lease)",
        ["Stats.Title"] = "Repository statistics",
        ["Stats.Commits"] = "Commits",
        ["Stats.Branches"] = "Branches",
        ["Stats.Tags"] = "Tags",
        ["Stats.LastActivity"] = "Last activity",
        ["Stats.Contributors"] = "Contributors",
        ["Stats.Loading"] = "Loading…",
        ["Config.Title"] = "Git config",
        ["Config.Tip"] = "Edit Git settings such as your name and email. Turn on 'Apply globally' to affect every repository (--global).",
        ["Config.UserName"] = "Name (user.name)",
        ["Config.UserEmail"] = "Email (user.email)",
        ["Config.Local"] = "This repository",
        ["Config.Global"] = "Apply globally (--global)",
        ["Config.SetCustom"] = "Set another key…",
        ["Config.KeyPrompt"] = "Config key (e.g. core.editor)",
        ["Config.ValuePrompt"] = "Value",
        ["Common.Save"] = "Save",
        ["Menu.Hosting"] = "PRs & issues (GitHub/GitLab)…",
        ["Menu.OpenInEditor"] = "Open in editor (VS Code)",
        ["Ctx.OpenInEditor"] = "Open in editor",
        ["Ctx.ExternalDiff"] = "Open in external diff tool",
        ["Hosting.Title"] = "Pull requests & issues",
        ["Hosting.PullRequests"] = "Pull requests",
        ["Hosting.Issues"] = "Issues",
        ["Hosting.Loading"] = "Loading…",
        ["Hosting.Empty"] = "No open PRs or issues. (Supported remote + token required.)",
        ["Hosting.Open"] = "Open",
        ["Hosting.Comments"] = "Comments",
        ["Hosting.CommentsSelectPrompt"] = "Select a PR or issue to view its comments.",
        ["Hosting.CommentsLoading"] = "Loading comments…",
        ["Hosting.CommentsEmpty"] = "No comments yet.",
        ["Hosting.NewComment"] = "New comment",
        ["Hosting.PostComment"] = "Post comment",
        ["Hosting.Posting"] = "Posting…",
        ["Hosting.CommentPosted"] = "Comment posted.",
        ["Hosting.CommentPostFailed"] = "Failed to post the comment. Check that your token has write access.",
        ["CI.Success"] = "CI passed",
        ["CI.Pending"] = "CI running",
        ["CI.Failure"] = "CI failed",
        ["Auth.DeviceTitle"] = "Sign in to GitHub",
        ["Auth.DeviceNotConfigured"] = "OAuth device sign-in needs a registered GitHub OAuth App client_id. For now, authentication uses a Personal Access Token (PAT).",
        ["Branch.PruneMerged"] = "Prune merged branches",
        ["Branch.PruneMerged.Tip"] = "Delete local branches already merged into the current branch (keeps main/master/develop).",
        ["Branch.PruneConfirm"] = "Delete these branches? {0}",
        ["Branch.NoStale"] = "No merged branches to prune.",
        ["Diff.IgnoreWhitespace"] = "Ignore whitespace",
        ["Diff.ExpandContext"] = "+context",
        ["Diff.ExpandContext.Tip"] = "Show more surrounding (context) lines around each change.",
        ["Diff.ShrinkContext"] = "−context",
        ["Diff.ShrinkContext.Tip"] = "Reduce context lines back toward the default.",
        ["Diff.ImageOld"] = "Before",
        ["Diff.ImageNew"] = "After",
        ["Menu.Advanced"] = "Advanced",
        ["Menu.Tools"] = "Tools",
        ["Menu.Tools.Tip"] = "More actions (reflog · compare · search · remotes · worktrees · LFS…)",
        ["Menu.Worktrees"] = "Worktrees…",
        ["Menu.Lfs"] = "Git LFS…",
        ["Menu.Submodules"] = "Submodules…",
        ["Menu.Sparse"] = "Sparse checkout…",
        ["Menu.Credentials"] = "Saved credentials…",
        ["Menu.Keybindings"] = "Keyboard shortcuts…",

        // Keybindings dialog
        ["Keybind.Title"] = "Keyboard shortcuts",
        ["Keybind.Tip"] = "View and customize the shortcut for each action. If two actions share a key, they're highlighted in red below.",
        ["Keybind.Col.Action"] = "Action",
        ["Keybind.Col.Shortcut"] = "Shortcut",
        ["Keybind.Rebind"] = "Rebind",
        ["Keybind.PressKey"] = "Press a key…",
        ["Keybind.Reset"] = "Reset",
        ["Keybind.ResetAll"] = "Reset all",
        ["Keybind.Customized"] = "(modified)",
        ["Keybind.Conflict"] = "Conflicts with another shortcut",
        ["Keybind.ConflictBanner"] = "Some shortcuts overlap — only one of the conflicting actions can fire. Rebind one of them below.",
        ["Keybind.Action.OpenRepository"] = "Open repository",
        ["Keybind.Action.CreateRepository"] = "Create repository",
        ["Keybind.Action.CommandPalette"] = "Open command palette",
        ["Keybind.Action.FocusSearch"] = "Focus search",
        ["Keybind.Action.CloseTab"] = "Close tab",
        ["Keybind.Action.NextTab"] = "Next tab",
        ["Keybind.Action.PreviousTab"] = "Previous tab",
        ["Keybind.Action.Refresh"] = "Refresh",
        ["Keybind.Action.Fetch"] = "Fetch",
        ["Keybind.Action.Commit"] = "Commit",

        ["Common.OK"] = "OK",
        ["Common.Cancel"] = "Cancel",
        ["Common.Yes"] = "Yes",
        ["Common.No"] = "No",
        ["Common.Close"] = "Close",
        ["Common.Error"] = "Error",
        ["Common.Warning"] = "Warning",
        ["Common.Success"] = "Done",
        ["Common.Delete"] = "Delete",
        ["Confirm.DiscardTitle"] = "Discard changes?",
        ["Confirm.DiscardBody"] = "Edits to '{0}' will be lost and cannot be recovered. Continue?",
        ["Confirm.DeleteBranchTitle"] = "Delete branch?",
        ["Confirm.DeleteBranchBody"] = "The branch '{0}' will be deleted. Continue?",
        ["Error.OpenFailed"] = "Couldn't open the repository",
        ["Error.GitFailed"] = "The Git command failed",
        ["Error.NotARepo"] = "The selected folder is not a Git repository.",

        ["Time.JustNow"] = "just now",
        ["Time.MinutesAgo"] = "{0} min ago",
        ["Time.HoursAgo"] = "{0} h ago",
        ["Time.DaysAgo"] = "{0} d ago",
        ["Time.MonthsAgo"] = "{0} mo ago",
        ["Time.YearsAgo"] = "{0} y ago",
    };
}
