using System.Text;

namespace GitTab.Core.Gitignore;

public sealed class GitignoreTemplate
{
    public required string Key { get; init; }
    public required string Name { get; init; }
    public required string Content { get; init; }
}

/// <summary>Generates a .gitignore from bundled, stack-specific templates, with auto-detection.</summary>
public interface IGitignoreService
{
    IReadOnlyList<GitignoreTemplate> Templates { get; }

    /// <summary>Template keys whose marker files are present under <paramref name="workingDir"/>.</summary>
    IReadOnlyList<string> Detect(string workingDir);

    /// <summary>Concatenates the selected templates into a single .gitignore body.</summary>
    string Build(IEnumerable<string> keys);

    string? ReadExisting(string workingDir);

    /// <summary>Writes (or appends) the content to <c>{workingDir}/.gitignore</c>.</summary>
    void Write(string workingDir, string content, bool append);
}

public sealed class GitignoreService : IGitignoreService
{
    private static readonly (string Key, string Name, string[] Markers, string[] MarkerGlobs)[] Detectors =
    {
        ("dotnet", ".NET / Visual Studio", new[] { "*.sln", "*.csproj", "*.fsproj", "*.vbproj" }, Array.Empty<string>()),
        ("node",   "Node.js",              new[] { "package.json" }, Array.Empty<string>()),
        ("python", "Python",               new[] { "requirements.txt", "pyproject.toml", "setup.py", "Pipfile" }, new[] { "*.py" }),
        ("java",   "Java (Gradle/Maven)",  new[] { "pom.xml", "build.gradle", "build.gradle.kts", "settings.gradle" }, Array.Empty<string>()),
        ("rust",   "Rust (Cargo)",         new[] { "Cargo.toml" }, Array.Empty<string>()),
        ("go",     "Go",                   new[] { "go.mod" }, Array.Empty<string>()),
        ("flutter","Flutter / Dart",       new[] { "pubspec.yaml" }, Array.Empty<string>()),
        ("unity",  "Unity",                new[] { "ProjectSettings/ProjectVersion.txt" }, Array.Empty<string>()),
    };

    public IReadOnlyList<GitignoreTemplate> Templates { get; } = BuildTemplateList();

    public IReadOnlyList<string> Detect(string workingDir)
    {
        var found = new List<string>();
        if (string.IsNullOrWhiteSpace(workingDir) || !Directory.Exists(workingDir))
            return found;

        foreach (var (key, _, markers, globs) in Detectors)
        {
            if (markers.Any(m => MarkerExists(workingDir, m)) || globs.Any(g => AnyFileMatches(workingDir, g)))
                found.Add(key);
        }
        // The OS/editor "global" template is always a good idea.
        found.Add("global");
        return found;
    }

    public string Build(IEnumerable<string> keys)
    {
        var byKey = Templates.ToDictionary(t => t.Key, StringComparer.Ordinal);
        var sb = new StringBuilder();
        sb.Append("# Generated by Git Tab\n");
        foreach (var key in keys.Distinct())
        {
            if (!byKey.TryGetValue(key, out var t)) continue;
            sb.Append('\n').Append("### ").Append(t.Name).Append(" ###\n").Append(t.Content.TrimEnd('\n')).Append('\n');
        }
        return sb.ToString();
    }

    public string? ReadExisting(string workingDir)
    {
        var path = Path.Combine(workingDir, ".gitignore");
        return File.Exists(path) ? File.ReadAllText(path) : null;
    }

    public void Write(string workingDir, string content, bool append)
    {
        var path = Path.Combine(workingDir, ".gitignore");
        if (append && File.Exists(path))
        {
            var existing = File.ReadAllText(path).TrimEnd('\n');
            File.WriteAllText(path, existing + "\n\n" + content.TrimStart('\n'));
        }
        else
        {
            File.WriteAllText(path, content);
        }
    }

    // ---- detection helpers (bounded depth, skips heavy dirs) ----

    private static readonly HashSet<string> SkipDirs = new(StringComparer.OrdinalIgnoreCase)
        { ".git", "node_modules", "bin", "obj", ".vs", ".idea", "target", "build", "dist", ".gradle" };

    private static bool MarkerExists(string root, string marker)
    {
        if (marker.Contains('/'))
            return File.Exists(Path.Combine(root, marker.Replace('/', Path.DirectorySeparatorChar)));
        if (marker.Contains('*'))
            return AnyFileMatches(root, marker);
        return File.Exists(Path.Combine(root, marker));
    }

    private static bool AnyFileMatches(string root, string glob, int maxDepth = 3)
    {
        var queue = new Queue<(string Dir, int Depth)>();
        queue.Enqueue((root, 0));
        while (queue.Count > 0)
        {
            var (dir, depth) = queue.Dequeue();
            try
            {
                if (Directory.EnumerateFiles(dir, glob, SearchOption.TopDirectoryOnly).Any())
                    return true;
                if (depth < maxDepth)
                {
                    foreach (var sub in Directory.EnumerateDirectories(dir))
                    {
                        var name = Path.GetFileName(sub);
                        if (!SkipDirs.Contains(name) && !name.StartsWith('.'))
                            queue.Enqueue((sub, depth + 1));
                    }
                }
            }
            catch (UnauthorizedAccessException) { /* skip */ }
            catch (IOException) { /* skip */ }
        }
        return false;
    }

    private static List<GitignoreTemplate> BuildTemplateList() => new()
    {
        new() { Key = "dotnet", Name = ".NET / Visual Studio", Content =
            "bin/\nobj/\n[Dd]ebug/\n[Rr]elease/\nx64/\nx86/\n.vs/\n*.user\n*.suo\n*.userosscache\n*.sln.docstates\npublish/\ndist/\n[Rr]eleases/\nTestResults/\n*.nupkg\n*.snupkg\nproject.lock.json\nartifacts/\n" },
        new() { Key = "node", Name = "Node.js", Content =
            "node_modules/\nnpm-debug.log*\nyarn-debug.log*\nyarn-error.log*\npnpm-debug.log*\n.pnp.*\ndist/\nbuild/\ncoverage/\n.cache/\n.next/\n.nuxt/\n.parcel-cache/\n.env\n.env.local\n.env.*.local\n.DS_Store\n" },
        new() { Key = "python", Name = "Python", Content =
            "__pycache__/\n*.py[cod]\n*$py.class\n*.egg-info/\n*.egg\n.eggs/\nbuild/\ndist/\n.venv/\nvenv/\nenv/\nENV/\n.pytest_cache/\n.mypy_cache/\n.ruff_cache/\n.coverage\nhtmlcov/\n.ipynb_checkpoints/\n.python-version\n" },
        new() { Key = "java", Name = "Java (Gradle/Maven)", Content =
            "*.class\ntarget/\nbuild/\n.gradle/\n!gradle/wrapper/gradle-wrapper.jar\n*.war\n*.ear\n.settings/\n.classpath\n.project\nhs_err_pid*\nreplay_pid*\n" },
        new() { Key = "rust", Name = "Rust (Cargo)", Content =
            "/target/\n**/*.rs.bk\n*.pdb\n" },
        new() { Key = "go", Name = "Go", Content =
            "bin/\n/vendor/\n*.exe\n*.exe~\n*.dll\n*.so\n*.dylib\n*.test\n*.out\ngo.work.sum\n" },
        new() { Key = "flutter", Name = "Flutter / Dart", Content =
            ".dart_tool/\n.packages\n.pub-cache/\n.pub/\nbuild/\n.flutter-plugins\n.flutter-plugins-dependencies\n*.iml\n.idea/\n.gradle/\nlocal.properties\n" },
        new() { Key = "unity", Name = "Unity", Content =
            "[Ll]ibrary/\n[Tt]emp/\n[Oo]bj/\n[Bb]uild/\n[Bb]uilds/\n[Ll]ogs/\n[Uu]serSettings/\n*.csproj\n*.unityproj\n*.sln\n*.userprefs\n*.unitypackage\n*.pidb\n" },
        new() { Key = "global", Name = "OS & editors (global)", Content =
            "# OS\n.DS_Store\nThumbs.db\nDesktop.ini\n$RECYCLE.BIN/\n\n# Editors\n.vscode/\n.idea/\n*.swp\n*.swo\n*~\n\n# Logs\n*.log\n" },
    };
}
